New canvas feature
sschuraytz/CharcoalDrawing_AndroidApp pull request #2
Opened 2020-05-15 19:16 UTC by sschuraytz

The newest commits in this branch are for an eraser. It may not be used in the final project, but I'm testing out functionality.
Right now, the eraser does not create a smooth line.

2020-06-10 17:16 UTC, sschuraytz commented
![image](https://user-images.githubusercontent.com/44480876/84298074-640c4a00-ab03-11ea-8e36-69fe83524ba4.png)

2020-06-28 23:26 UTC, andrewoid requested changes
I can see why drawing no longer works after clearing the screen.

This is a bug you need to find yourself.

2020-06-28 23:26 UTC, andrewoid commented on app/src/main/java/com/sschuraytz/charcoaldrawing/UndoRedo.java
> +    public void resetButtonsForNewCanvas() {
This method does a little more than reset buttons. Actually one of the advantages of UndoRedo is that it doesn't know what is reacting to it so this method shouldn't have "buttons" in it.

2020-06-29 17:34 UTC, andrewoid approved these changes

2020-06-29 17:44 UTC, merged