Create textured dots
sschuraytz/CharcoalDrawing_AndroidApp pull request #5
Opened 2020-05-24 06:26 UTC by sschuraytz

2020-05-24 12:47 UTC, andrewoid requested changes

2020-05-24 12:47 UTC, andrewoid commented on app/src/main/java/com/sschuraytz/charcoaldrawing/DrawingView.java
> +        rand = new Random();
There is no reason to create Random each time (and you aren't using it).
Create it once.

2020-05-24 12:47 UTC, andrewoid commented on app/src/main/java/com/sschuraytz/charcoaldrawing/DrawingView.java
> +            angle = ThreadLocalRandom.current().nextInt(0, 360 + 1);
Use `rand` variable instead.

2020-05-24 12:47 UTC, andrewoid commented on app/src/main/java/com/sschuraytz/charcoaldrawing/DrawingView.java
> +                printTexturedCircle(pointX, pointY);
You are creating a new circle each time you draw it.
Instead, draw it to a separate bitmap once, then draw the bitmap to canvasBitmap each time you want to draw the circle.

2020-06-01 19:48 UTC, andrewoid commented on app/src/main/java/com/sschuraytz/charcoaldrawing/DrawingView.java
>                  path.moveTo(pointX, pointY);
You are no longer using `path`

2020-06-01 19:50 UTC, andrewoid approved these changes

2020-06-05 11:07 UTC, sschuraytz commented
Drawing with charcoal tool of varying thicknesses:
![image](https://user-images.githubusercontent.com/44480876/83869835-0d0d0c00-a6e2-11ea-91f7-9f29e8be2f5b.png)

2020-06-05 13:05 UTC, andrewoid approved these changes

2020-06-05 13:05 UTC, andrewoid commented on app/src/main/java/com/sschuraytz/charcoaldrawing/CharcoalTool.java
> +    private void createCircleWithNoLocation()
It's weird to have a method, with no arguments, just call another method with no arguments.

2020-06-05 20:22 UTC, merged